Update server-5.0: remove baron acct and make root host %.  Add kill cmd to mk-test-env.  Remove server.tar.gz (no longer used).
git-svn-id: http://maatkit.googlecode.com/svn/trunk@5745 dfb901c2-3250-0410-b216-0b33211c9131

diff --git a/sandbox/mk-test-env b/sandbox/mk-test-env
--- a/sandbox/mk-test-env
+++ b/sandbox/mk-test-env
@@ -22,14 +22,23 @@ _d() {
 err() {
    echo
    for msg; do
-      echo $msg
+      echo "$msg"
    done
    echo "See http://code.google.com/p/maatkit/wiki/Testing for more information."
    echo
 }
 
 usage() {
-   err "Usage: mk-test-env start|stop|restart|status|checkconfig"
+   err "Usage: mk-test-env start|stop|restart|status|checkconfig|reset|kill" \
+       ""                                                               \
+       "  start       Start Maatkit test environment (mk test env)"     \
+       "  stop        Stop and remove mk test env"                      \
+       "  restart     Stop and start mk test env"                       \
+       "  status      Check and display status of mk test env"          \
+       "  checkconfig Check and display configuration of mk test env"   \
+       "  reset       Reset mk test env master/slave bin logs"          \
+       "  kill        Kill mk test env (use if stop fails)"             \
+       "" 
 }
 
 mysql_basedir_ok() {
@@ -183,6 +192,55 @@ sandbox_status() {
    return $status
 }
 
+sandbox_is_running() {
+   local p=$1
+   ps axw | grep mysqld | grep /tmp/$p >/dev/null
+}
+
+kill_sandbox() {
+   local p=$1
+   local rmdir=1
+
+   # See if the sandbox server is running.
+   sandbox_is_running $p
+   if [ $? -eq 0 ]; then
+      # Try to kill it with mysqladmin shutdown.  We try different
+      # user/pass because sometimes a test can bork acct privs.
+      mysqladmin -h127.1 -P$p -umsandbox -pmsandbox shutdown >/dev/null 2>&1
+      mysqladmin -h127.1 -P$p -uroot -pmsandbox shutdown >/dev/null 2>&1
+      mysqladmin -h127.1 -P$p -uroot shutdown >/dev/null 2>&1
+
+      # See if the sandbox server is still running.
+      sandbox_is_running $p 
+      if [ $? -eq 0 ]; then
+         # Kill both mysqld_safe and mysqld.
+         pid1=`ps axw | grep mysqld_safe | grep /tmp/$p | awk '{print $1}'`
+         pid2=`ps axw | grep mysqld | grep -v mysqld_safe | grep /tmp/$p | awk '{print $1}'`
+         kill -9 $pid1  # Die, damn you, die!
+         kill -9 $pid2
+         sleep 1
+
+         # Third and finaly check if the sandbox server is running.
+         sandbox_is_running $p
+         if [ $? -eq 0 ]; then
+            err "Failed to kill sandbox $p (PID $pid1, $pid2)"
+            rmdir=0
+         else 
+            echo "Killed sandbox $p (PID $pid1, $pid2)"
+         fi
+      else
+         echo "Killed sandbox $p"
+      fi
+   fi
+
+   if [ $rmdir -eq 1 ] && [ -d "/tmp/$p" ]; then
+      rm -rf /tmp/$p
+      echo "Removed /tmp/$p"
+   fi
+
+   return
+}
+
 # ###########################################################################
 # Sanity check the cmd line options.
 # ###########################################################################
@@ -254,6 +312,13 @@ case $opt in
          err "There was an error stopping the Maatkit test environment." \
              "The Maatkit sandboxes may still be running."
       fi
+      ;;
+   kill)
+      # This is a blunt approach for killing the entire mk test env
+      # when a polite stop fails.  It uses kill -9 as a last resort.
+      for port in 12345 12346 12347 12348 12349 2900 2901 2902 2903; do
+         kill_sandbox $port
+      done
       ;;
    restart)
       $0 stop
